/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _IndexRoute } from '../pages/';
import { Route as _IntakeRoute } from '../pages/intake';
import { Route as _PaymentTossFailRoute } from '../pages/payment/toss/fail';
import { Route as _PaymentTossSuccessRoute } from '../pages/payment/toss/success';
import { Route as _PreviewStructuredReportRoute } from '../pages/preview/structured-report';
import { Route as _ToolsRoute } from '../pages/tools';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/': (typeof _IndexRoute)['_inputType'];
    '/intake': (typeof _IntakeRoute)['_inputType'];
    '/payment/toss/fail': (typeof _PaymentTossFailRoute)['_inputType'];
    '/payment/toss/success': (typeof _PaymentTossSuccessRoute)['_inputType'];
    '/preview/structured-report': (typeof _PreviewStructuredReportRoute)['_inputType'];
    '/tools': (typeof _ToolsRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/': (typeof _IndexRoute)['_outputType'];
    '/intake': (typeof _IntakeRoute)['_outputType'];
    '/payment/toss/fail': (typeof _PaymentTossFailRoute)['_outputType'];
    '/payment/toss/success': (typeof _PaymentTossSuccessRoute)['_outputType'];
    '/preview/structured-report': (typeof _PreviewStructuredReportRoute)['_outputType'];
    '/tools': (typeof _ToolsRoute)['_outputType'];
  }
}
